name: Check assignment code

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile with Maven
        run: mvn --batch-mode --update-snapshots compile
      - name: Test 1
        run: mvn --batch-mode --update-snapshots test -Dtest=TittebygdaTest
      - name: Test 2
        run: mvn --batch-mode --update-snapshots test -Dtest=SveleOgKaffiQueueTest
